using FileOrganizer.Core.Watcher;
using FileOrganizer.Shared.Models;

namespace FileOrganizer.Core.Tests.Watcher;

public sealed class WatcherServiceTests : IDisposable
{
    private readonly string _folder = Path.Combine(
        Path.GetTempPath(), "FileOrganizerTests", "WatcherService", Guid.NewGuid().ToString("N"));

    public WatcherServiceTests() => Directory.CreateDirectory(_folder);

    [Fact]
    public async Task StartAsync_起動前の既存ファイルは再走査でも処理せず新規ファイルだけ通知する()
    {
        string existingPath = Path.Combine(_folder, "existing.txt");
        File.WriteAllText(existingPath, "existing");
        await using var service = new WatcherService(stabilityCheckIntervalMs: 50, periodicScanIntervalHours: 24);
        var stabilized = new TaskCompletionSource<string>(TaskCreationOptions.RunContinuationsAsynchronously);
        service.FileStabilized += (_, e) => stabilized.TrySetResult(e.Metadata.FullPath);

        await service.StartAsync([new WatchFolderSetting { Path = _folder, Enabled = true }]);
        await service.RescanAsync();
        await Task.Delay(400);
        Assert.False(stabilized.Task.IsCompleted, "起動前からあるファイルは自動処理してはならない。");

        string newPath = Path.Combine(_folder, "new.txt");
        File.WriteAllText(newPath, "new");
        string actual = await stabilized.Task.WaitAsync(TimeSpan.FromSeconds(5));
        Assert.Equal(newPath, actual);
    }

    [Fact]
    public async Task SuppressPath_自アプリ操作として登録した移動先イベントを通知しない()
    {
        await using var service = new WatcherService(stabilityCheckIntervalMs: 50, periodicScanIntervalHours: 24);
        var stabilized = new TaskCompletionSource<string>(TaskCreationOptions.RunContinuationsAsynchronously);
        service.FileStabilized += (_, e) => stabilized.TrySetResult(e.Metadata.FullPath);
        await service.StartAsync([new WatchFolderSetting { Path = _folder, Enabled = true }]);

        string path = Path.Combine(_folder, "self-generated.txt");
        service.SuppressPath(path, TimeSpan.FromSeconds(5));
        File.WriteAllText(path, "generated by organizer");

        Task completed = await Task.WhenAny(stabilized.Task, Task.Delay(TimeSpan.FromSeconds(1)));
        Assert.NotSame(stabilized.Task, completed);
    }

    public void Dispose()
    {
        try { Directory.Delete(_folder, recursive: true); } catch { }
    }
}
