<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- FileOrganizer.Core が net10.0-windows のため合わせる -->
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileOrganizer.Core\FileOrganizer.Core.csproj" />
  </ItemGroup>

</Project>
