<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileOrganizer.Core\FileOrganizer.Core.csproj" />
    <ProjectReference Include="..\FileOrganizer.Infrastructure\FileOrganizer.Infrastructure.csproj" />
    <ProjectReference Include="..\FileOrganizer.Shared\FileOrganizer.Shared.csproj" />
    <ProjectReference Include="..\FileOrganizer.Widgets\FileOrganizer.Widgets.csproj" />
  </ItemGroup>

</Project>
